//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YifanLu.DumpMemory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YifanLu.DumpMemory.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get expression context for current stack frame.
        /// </summary>
        internal static string CannotGetExprContextErrorText {
            get {
                return ResourceManager.GetString("CannotGetExprContextErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get context for current frame.
        /// </summary>
        internal static string CannotGetFrameErrorText {
            get {
                return ResourceManager.GetString("CannotGetFrameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find memory reference from debugee program.
        /// </summary>
        internal static string CannotGetMemoryErrorText {
            get {
                return ResourceManager.GetString("CannotGetMemoryErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} bytes unreadable from this chunk..
        /// </summary>
        internal static string ChunkUnreadableErrorText {
            get {
                return ResourceManager.GetString("ChunkUnreadableErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get IVsDebugger service.
        /// </summary>
        internal static string DebuggerServiceNotFound {
            get {
                return ResourceManager.GetString("DebuggerServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find DTE service.
        /// </summary>
        internal static string DTEServiceNotFound {
            get {
                return ResourceManager.GetString("DTEServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error dumping: {0} ({1} bytes left).
        /// </summary>
        internal static string DumpErrorText {
            get {
                return ResourceManager.GetString("DumpErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump complete..
        /// </summary>
        internal static string DumpSuccessText {
            get {
                return ResourceManager.GetString("DumpSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot evaluate address.
        /// </summary>
        internal static string ExpressionEvalErrorText {
            get {
                return ResourceManager.GetString("ExpressionEvalErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        internal static string InputBrowseTitle {
            get {
                return ResourceManager.GetString("InputBrowseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length..
        /// </summary>
        internal static string InvalidLengthErrorText {
            get {
                return ResourceManager.GetString("InvalidLengthErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading: {0} ({1} bytes written).
        /// </summary>
        internal static string LoadErrorText {
            get {
                return ResourceManager.GetString("LoadErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load complete..
        /// </summary>
        internal static string LoadSuccessText {
            get {
                return ResourceManager.GetString("LoadSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in debugging context.
        /// </summary>
        internal static string NotInDebugContextErrorText {
            get {
                return ResourceManager.GetString("NotInDebugContextErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file.
        /// </summary>
        internal static string OutputBrowseTitle {
            get {
                return ResourceManager.GetString("OutputBrowseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing expression (void *)({0}) (error: {1}).
        /// </summary>
        internal static string ParseExpressionErrorText {
            get {
                return ResourceManager.GetString("ParseExpressionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string SuccessDialogTitle {
            get {
                return ResourceManager.GetString("SuccessDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Memory.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization failed: debug interface not found.
        /// </summary>
        internal static string VSInternalMethodsNotFoundErrorText {
            get {
                return ResourceManager.GetString("VSInternalMethodsNotFoundErrorText", resourceCulture);
            }
        }
    }
}
